name: project hotel booking

on:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout cicd  
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: go build
      run: go build

    - name: go testing
      run: go test -v ./...

      deploy:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: Deploy to production
      run: |
        echo "Deploying to production"

        # SSH into the production server
        ssh Shaikh@icrode-booking.online
          cd /path/to/your/app

          # Pull the latest changes from the repository
          git pull
          
          npm install

          go run main.go
     
